In [2]:
import sys
sys.path.append('..')
from rl import ppo

observation_space = (1,)
discount_rate = 0.99
lam = 0.95

memory = ppo.PPOReplayMemory(2_000, observation_space, gamma=discount_rate, lam=lam, gather_next_states=True)

# states, actions, rewards, values, log_probs, next_states, dones
# prep so data of shape
# (200, 100, 11)
# there: 200 - number of steps
# 100 - number of parallel environments
# 11 - observation space
# to make it clear put index of parallel environment in first observation and index of step in second observation

In [3]:
import numpy as np

# lets assume 2 par env with 10 steps each
states = [
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
]
actions = [
    [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
    [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
]
rewards = [
    [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
    [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
]
values = [
    [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
    [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
]
log_probs = [
     [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
    [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
]
next_states = [
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
]
dones = [
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
] 

# convert to numpy array, transpose and reshape
states = np.array(states).T.reshape(10, 2, 1)
actions = np.array(actions).T.reshape(10, 2)
rewards = np.array(rewards).T.reshape(10, 2)
values = np.array(values).T.reshape(10, 2)
log_probs = np.array(log_probs).T.reshape(10, 2)
next_states = np.array(next_states).T.reshape(10, 2, 1)
dones = np.array(dones).T.reshape(10, 2)



import tensorflow as tf

# convert to tf.Tensor
states = tf.constant(states, dtype=tf.uint8)
actions = tf.constant(actions, dtype=tf.int32)
rewards = tf.constant(rewards, dtype=tf.float32)
values = tf.constant(values, dtype=tf.float32)
log_probs = tf.constant(log_probs, dtype=tf.float32)
next_states = tf.constant(next_states, dtype=tf.uint8)
dones = tf.constant(dones, dtype=tf.float32)

In [4]:
states.shape

TensorShape([10, 2, 1])

In [5]:
states_np = states.numpy()
dones_np = dones.numpy()

In [6]:
states_np

array([[[ 1],
        [11]],

       [[ 2],
        [12]],

       [[ 3],
        [13]],

       [[ 4],
        [14]],

       [[ 5],
        [15]],

       [[ 6],
        [16]],

       [[ 7],
        [17]],

       [[ 8],
        [18]],

       [[ 9],
        [19]],

       [[10],
        [20]]], dtype=uint8)

In [7]:
# add to memory
memory.add_multiple(states, actions, rewards, values, log_probs, next_states, dones)

[[[ 1]
  [11]]

 [[ 2]
  [12]]

 [[ 3]
  [13]]

 [[ 4]
  [14]]

 [[ 5]
  [15]]

 [[ 6]
  [16]]

 [[ 7]
  [17]]

 [[ 8]
  [18]]

 [[ 9]
  [19]]

 [[10]
  [20]]]
[[1]
 [2]
 [3]
 ...
 [0]
 [0]
 [0]]
[[0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]]
0


In [11]:
states_buf = memory.states_buffer.numpy()
# display whole array
np.set_printoptions(threshold=sys.maxsize)
print(states_buf)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [13]
 [14]
 [15]
 [16]
 [17]
 [19]
 [20]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0